#  Topic : Simple Linear Regression

## Importing packages

In [7]:

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

### Data 

In [8]:
# Rocket Propellent Data from Montgomery's Book Regression Analysis
y = np.array([2158.7,1678.15,2316,2061.3,2207.5,1708.3,1784.7,2575,2357.9,2256.7,2165.2,2399.55,1779.8,2336.75,1765.3,2053.5,2414.4,2200.5,2654.2,1753.7])
x = np.array([15.5,23.75,8,17,5.5,19,24,2.5,7.5,11,13,3.75,25,9.75,22,18,6,12.5,2,21.5]).reshape(-1,1)

Now, you have two arrays: the input x and output y. You should call .reshape() on x because this array is required to be two-dimensional, or to be more precise, to have one column and as many rows as necessary. That’s exactly what the argument (-1, 1) of .reshape() specifies.

In [9]:
print("x.ndim : ",x.ndim)
print("y.ndim : ",y.ndim)

x.ndim :  2
y.ndim :  1


In [10]:
x

array([[15.5 ],
       [23.75],
       [ 8.  ],
       [17.  ],
       [ 5.5 ],
       [19.  ],
       [24.  ],
       [ 2.5 ],
       [ 7.5 ],
       [11.  ],
       [13.  ],
       [ 3.75],
       [25.  ],
       [ 9.75],
       [22.  ],
       [18.  ],
       [ 6.  ],
       [12.5 ],
       [ 2.  ],
       [21.5 ]])

In [11]:
y

array([2158.7 , 1678.15, 2316.  , 2061.3 , 2207.5 , 1708.3 , 1784.7 ,
       2575.  , 2357.9 , 2256.7 , 2165.2 , 2399.55, 1779.8 , 2336.75,
       1765.3 , 2053.5 , 2414.4 , 2200.5 , 2654.2 , 1753.7 ])

In [12]:
# Let’s create an instance of the class LinearRegression
model = LinearRegression()

In [13]:
model.fit(x, y)

LinearRegression()

### coefficient of determination ( R squared)

In [14]:

print('coefficient of determination R^2:', model.score(x, y))

coefficient of determination R^2: 0.9018414316763039


###  Code for intercept term

In [15]:
print('intercept:', model.intercept_) # intercept Scaler

intercept: 2627.8223590012963


###  Code for slope term

In [16]:
print('slope:', model.coef_) # Array Quantity

slope: [-37.15359094]


### Prediction of response values

In [17]:

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
y_pred.ndim

predicted response:
[2051.94169936 1745.42457406 2330.59363144 1996.21131294 2423.4776088
 1921.90413105 1736.13617632 2534.93838164 2349.17042691 2219.13285861
 2144.82567672 2488.49639296 1698.98258538 2265.57484729 1810.44335821
 1959.05772199 2404.90081333 2163.40247219 2553.51517711 1829.02015369]


1

###  Another way of  predicting response

In [18]:

y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')
y_pred.ndim

predicted response:
[[2051.94169936]
 [1745.42457406]
 [2330.59363144]
 [1996.21131294]
 [2423.4776088 ]
 [1921.90413105]
 [1736.13617632]
 [2534.93838164]
 [2349.17042691]
 [2219.13285861]
 [2144.82567672]
 [2488.49639296]
 [1698.98258538]
 [2265.57484729]
 [1810.44335821]
 [1959.05772199]
 [2404.90081333]
 [2163.40247219]
 [2553.51517711]
 [1829.02015369]]


2

## Concatenating of  x , actual y, predicted y

In [19]:
pd.DataFrame({"X":np.concatenate(x),
              "Actual":y,
              "Predicted":np.concatenate(y_pred)})

X   Actual    Predicted
0   15.50  2158.70  2051.941699
1   23.75  1678.15  1745.424574
2    8.00  2316.00  2330.593631
3   17.00  2061.30  1996.211313
4    5.50  2207.50  2423.477609
5   19.00  1708.30  1921.904131
6   24.00  1784.70  1736.136176
7    2.50  2575.00  2534.938382
8    7.50  2357.90  2349.170427
9   11.00  2256.70  2219.132859
10  13.00  2165.20  2144.825677
11   3.75  2399.55  2488.496393
12  25.00  1779.80  1698.982585
13   9.75  2336.75  2265.574847
14  22.00  1765.30  1810.443358
15  18.00  2053.50  1959.057722
16   6.00  2414.40  2404.900813
17  12.50  2200.50  2163.402472
18   2.00  2654.20  2553.515177
19  21.50  1753.70  1829.020154

### Predicting value of y for  x = 18

In [20]:
model.predict(np.array([18]).reshape(-1, 1))

array([1959.05772199])

In [21]:
model.predict([[18]])

array([1959.05772199])

# Multiple Linear Regression

###  Data

In [23]:
data=pd.read_csv("DeliveryTimeData.csv")

###  no. of observations

In [ ]:
n=data.shape[0] # Number of Observations
n

In [ ]:
X=data.iloc[:,2:]
y=data.iloc[:,1]

### model

In [ ]:
model = LinearRegression().fit(X, y)

###  Code for obtaining :-
###                                     1]coefficient of determination
###                                     2]intercept term 
###                                     3]slope term

In [ ]:
print('coefficient of determination:',model.score(X, y))
print('intercept:', model.intercept_)
print('slope:', model.coef_)

### Prediction

In [ ]:
y_pred = model.predict(X)
print('predicted response:', y_pred, sep='\n')

### predicting value of y for x=20

In [ ]:
model.predict([[20]])

In [ ]:
data.head()

###  ANOVA

In [ ]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
model=ols('DeliveryTime~NumberOfCases+Distance',data).fit()

In [ ]:
model.summary()
anova_results = anova_lm(model)
anova_results