In [15]:
from numpy.random import *
import numpy as np
import pandas as pd

# Simple Random Data

In [2]:
#Random values in a given shape.

#rand(d0, d1, …, dn)
rand(5,2,3)

array([[[0.03770052, 0.02180855, 0.09806484],
        [0.06327816, 0.21114869, 0.79011666]],

       [[0.98389282, 0.53617025, 0.92449749],
        [0.71169146, 0.49129118, 0.55173678]],

       [[0.56848337, 0.47064529, 0.02789898],
        [0.40444621, 0.85005697, 0.76115312]],

       [[0.22694896, 0.60244064, 0.36879262],
        [0.03936633, 0.05324949, 0.7939857 ]],

       [[0.95209434, 0.57350449, 0.55998647],
        [0.58760393, 0.95814024, 0.69278556]]])

In [3]:
#Return a sample (or samples) from the “Standard Normal” distribution.

#randn(d0, d1, …, dn)
randn(5)

array([ 0.22235155,  0.62743129, -0.06943079, -1.53507303, -1.35851148])

In [4]:
#Return random integers from low (inclusive) to high (exclusive).

#randint(low[, high, size, dtype])
randint(5,10,10)

array([7, 5, 8, 8, 5, 5, 6, 5, 9, 9])

In [5]:
#Return random floats in the half-open interval [0.0, 1.0).

random_sample(5)

array([0.30337088, 0.57567457, 0.80959643, 0.09885197, 0.48978733])

In [6]:
#Return random floats in the half-open interval [0.0, 1.0).

#random([size])

In [7]:
#Return random floats in the half-open interval [0.0, 1.0).

#ranf([size])

In [8]:
#Return random floats in the half-open interval [0.0, 1.0).

#sample([size])

In [9]:
#Generates a random sample from a given 1-D array

#choice(a[, size, replace, p])

a=list(range(5))
print("a:",a)
list(choice(a,5,0))

a: [0, 1, 2, 3, 4]


[0, 4, 3, 2, 1]

# Permutations

In [10]:
#Modify a sequence in-place by shuffling its contents.

#shuffle(x)


print("x:",x)
shuffle(x)
print("After Shuffling x:",x)

NameError: name 'x' is not defined

In [ ]:
#Randomly permute a sequence, or return a permuted range.

#permutation(x)
x=np.arange(5)
permutation(x)
x

# Distributions

In [ ]:
#Draw samples from a Beta distribution.

#beta(a, b[, size])
beta(1,10,3)

In [ ]:
#Draw samples from a binomial distribution.

#binomial(n, p[, size])
np.mean(binomial(10,0.6,40))

In [ ]:
#Draw samples from a chi-square distribution.

#chisquare(df[, size])
chisquare(2,10)

In [ ]:
#Draw samples from an exponential distribution.

#exponential([scale, size])

In [ ]:
#Draw samples from an F distribution.

#f(dfnum, dfden[, size])

In [ ]:
#Draw samples from a Gamma distribution.

#gamma(shape[, scale, size])

In [ ]:
#Draw samples from the geometric distribution.

#geometric(p[, size])

In [ ]:
#Draw samples from a Gumbel distribution.

#gumbel([loc, scale, size])

In [ ]:
#Draw samples from a Hypergeometric distribution.

#hypergeometric(ngood, nbad, nsample[, size])

In [ ]:
#Draw samples from the Laplace or double exponential distribution with specified location (or mean) and scale (decay).

#laplace([loc, scale, size])

In [ ]:
#Draw samples from a logistic distribution.

#logistic([loc, scale, size])

In [ ]:
#Draw samples from a log-normal distribution.

#lognormal([mean, sigma, size])

In [ ]:
#Draw samples from a multinomial distribution.

#multinomial(n, pvals[, size])

In [ ]:
#Draw random samples from a multivariate normal distribution.

#multivariate_normal(mean, cov[, size, …)

In [ ]:
#Draw samples from a negative binomial distribution.

#negative_binomial(n, p[, size])

In [ ]:
#Draw samples from a noncentral chi-square distribution.

#noncentral_chisquare(df, nonc[, size])

In [ ]:
#Draw samples from the noncentral F distribution.

#noncentral_f(dfnum, dfden, nonc[, size])

In [ ]:
#Draw random samples from a normal (Gaussian) distribution.

#normal([loc, scale, size])
np.var(normal(10,4,1000))

In [ ]:
#Draw samples from a Pareto II or Lomax distribution with specified shape.

#pareto(a[, size])

In [ ]:
#Draw samples from a Poisson distribution.

#poisson([lam, size])

In [ ]:
#Draw samples from a standard Cauchy distribution with mode = 0.

#standard_cauchy([size])

In [ ]:
#Draw samples from the standard exponential distribution.

#standard_exponential([size])

In [ ]:
#Draw samples from a standard Gamma distribution.

#standard_gamma(shape[, size])

In [ ]:
#Draw samples from a standard Normal distribution (mean=0, stdev=1).

#standard_normal([size])
print(standard_normal(5))
print(randn(5))

In [ ]:
#Draw samples from a standard Student’s t distribution with df degrees of freedom.

#standard_t(df[, size])

In [ ]:
#Draw samples from the triangular distribution over the interval [left, right].

#triangular(left, mode, right[, size])

In [47]:
#Draw samples from a uniform distribution.
sizes=[5,10,25,50,100,200]
#uniform([low, high, size])
i=0
T1_avg,T1_mse,T2_avg,T2_mse=[0]*len(sizes),[0]*len(sizes),[0]*len(sizes),[0]*len(sizes)

for j in sizes:
    s=uniform(0,5,[1000,j])
    s1=pd.DataFrame(s,index=np.arange(1000)+1,columns=np.arange(j)+1)
    s1
    T1_avg[i]=np.mean(s1.apply(np.max,axis=1))
    T1_mse[i]=np.mean((s1.apply(np.max,axis=1)-5)**2)
    T2_avg[i]=np.mean(2*s1.apply(np.mean,axis=1))
    T2_mse[i]=np.mean((2*s1.apply(np.mean,axis=1)-5)**2)
    i=i+1
    
pd.DataFrame({"Size": sizes,
              "T1_Average": T1_avg,
              "T1_MSError": T1_mse,
              "T2_Average": T2_avg,
              "T2_MSError": T2_mse
    
})    

Size  T1_Average  T1_MSError  T2_Average  T2_MSError
0     5    4.169444    1.185433    4.999186    1.607469
1    10    4.540318    0.389094    5.004557    0.839234
2    25    4.815784    0.067386    4.992531    0.355729
3    50    4.898269    0.020588    4.984429    0.164616
4   100    4.950172    0.005054    4.993831    0.082935
5   200    4.974028    0.001301    5.009998    0.040073

In [31]:
np.mean((s1.apply(np.max,axis=1)-5)**2)

0.3002467943150209

In [34]:
np.mean((s1.apply(np.max,axis=1)-5)**2)

0.004010677543241804

In [ ]:
#Draw samples from a Weibull distribution.

#weibull(a[, size])