# Logistic Regression

## Importing the libraries

In [3]:
import numpy as np
import pandas as pd

## Importing the dataset

In [4]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
x_train.head()

Age  EstimatedSalary
78    28            87000
127   26            32000
254   50            44000
263   35            72000
293   37            77000

## Feature Scaling

In [38]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.49990399e+00, -1.23846715e+00],
       [ 7.86631842e-01, -3.15600997e-01],
       [ 1.54881045e+00,  9.82179526e-01],
       [-1.21408701e+00,  5.78425586e-01],
       [-1.02354236e+00,  5.20746451e-01],
       [ 2.44532305e-02,  1.21289606e+00],
       [-9.28270034e-01, -3.15600997e-01],
       [ 2.44532305e-02, -5.75157101e-01],
       [-8.32997708e-01, -6.61675803e-01],
       [ 1.19725557e-01,  3.04738093e-02],
       [-8.32997708e-01,  1.45832078e-01],
       [-7.08190960e-02,  2.61190347e-01],
       [ 2.44532305e-02, -4.30959265e-01],
       [ 2.14997883e-01,  2.32350780e-01],
       [-1.49990399e+00, -1.49802325e+00],
       [ 1.19725557e-01,  1.03985866e+00],
       [ 3.10270210e-01, -2.86761430e-01],
       [ 6.91359516e-01,  2.61190347e-01],
       [ 4.05542536e-01,  1.09753779e+00],
       [-1.02354236e+00, -4.59798833e-01],
       [ 1.54881045e+00,  1.63424214e-03],
       [ 7.86631842e-01,  5.20746451e-01],
       [-6.42453055e-01,  1.38593347e+00],
       [-7.

## Training the Logistic Regression model on the Training set

In [39]:
from sklearn.linear_model import LogisticRegression
LRclassifier=LogisticRegression()

LRclassifier.fit(x_train,y_train)

LogisticRegression()

## Predicting a new result

In [53]:
print(LRclassifier.predict(scaler.transform([[30,87000]])))

[1]


## Predicting the Test set results

In [62]:
y_pred=LRclassifier.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0], dtype=int64)

In [63]:
y_test

328    1
271    1
262    1
113    0
379    1
      ..
42     0
223    1
230    1
174    0
318    1
Name: Purchased, Length: 100, dtype: int64

## Making the Confusion Matrix

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test,y_pred)

array([[61,  5],
       [10, 24]], dtype=int64)

In [68]:
accuracy_score(y_test,y_pred)

0.85