# Import Libraries

In [2]:
#import numpy   # numpy.fun()
import numpy as np # np.fun()
#from numpy import * # fun()

# Matrix and vector products

In [4]:
a = np.array([[1, 0], [0, 1]]) # np.eye(2)
b = np.array([[4, 1], 
              [2, 2]])
print(a)
print(b)

[[1 0]
 [0 1]]
[[4 1]
 [2 2]]


In [5]:
a*b

array([[4, 0],
       [0, 2]])

# Dot product of two arrays.

In [4]:

np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [8]:
#Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.
A = np.random.random((2, 2))
B = np.random.random((2, 3))
C = np.random.random((3, 4))
D = np.random.random((4, 3))
# the actual dot multiplication
print(A)
print(B)
np.linalg.multi_dot([A, B, C, D])
# OR
# np.dot(np.dot(np.dot(A, B), C), D)
# OR
# A.dot(B).dot(C).dot(D)

[[0.92967541 0.58976342]
 [0.26649777 0.44124215]]
[[0.56330228 0.1747039  0.50731879]
 [0.46159748 0.33386143 0.39983338]]


array([[2.17374851, 1.12688012, 1.94912674],
       [0.99966863, 0.5205384 , 0.90096614]])

In [12]:
# np.dot(B,A) # shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
#Return the dot product of two vectors.
a = np.array([[1,4],
              [4,2]])
b = np.array([[3, 2],
              [2,3]])
np.vdot(a, b)

25

In [7]:
1*3+4*2+4*2+2*3

25

In [14]:
a=np.array([1,2])
b=np.array([3,4])
np.vdot(a,b)

11

In [17]:
#Inner product of two arrays. Matrix Multiplication
print(a)
print(b)
np.inner(a, b)

[[1 4]
 [4 2]]
[[3 2]
 [2 3]]


array([[11, 14],
       [16, 14]])

In [21]:
#Compute the outer product of two vectors.
a=np.array([1,2])
b=np.array([[2,3],[5,2]])
print(a)
print(b)
np.outer(a, b)

[1 2]
[[2 3]
 [5 2]]


array([[ 2,  3,  5,  2],
       [ 4,  6, 10,  4]])

In [23]:
#Matrix product of two arrays.
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1, 2],
              [2, 2, 3]])
np.matmul(a, b)

array([[4, 1, 2],
       [2, 2, 3]])

In [26]:
# The @ operator can be used as a shorthand for np.matmul on ndarrays.
a@b

array([[4, 1, 2],
       [2, 2, 3]])

In [34]:
#Raise a square matrix to the (integer) power n.
a=np.array([[1,2],[3,4]])
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [28]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

In [31]:
a@a@a

array([[ 37,  54],
       [ 81, 118]])

In [35]:
#Kronecker product of two arrays.
print(a)
print(b)
np.kron(a, b)

[[1 2]
 [3 4]]
[[4 1 2]
 [2 2 3]]


array([[ 4,  1,  2,  8,  2,  4],
       [ 2,  2,  3,  4,  4,  6],
       [12,  3,  6, 16,  4,  8],
       [ 6,  6,  9,  8,  8, 12]])

In [ ]:
#Decompositions

In [36]:
#Cholesky decomposition.
a=np.array([[6,15,55],
            [15,55,225],
            [55,225,979]])
np.linalg.cholesky(a)

array([[ 2.44948974,  0.        ,  0.        ],
       [ 6.12372436,  4.18330013,  0.        ],
       [22.45365598, 20.91650066,  6.11010093]])

In [42]:
np.linalg.matrix_rank(a)

3

In [46]:
#Compute the qr factorization of a matrix.
Q,R=np.linalg.qr(a)
print(Q)
print(R)

[[-0.10466885 -0.83044761 -0.54717566]
 [-0.26167214 -0.50781394  0.82076348]
 [-0.9594645   0.229089   -0.1641527 ]]
[[  -57.32364259  -231.84151249 -1003.94876177]
 [    0.            11.15854318    64.34537173]
 [    0.             0.            -6.12836734]]


In [51]:
np.linalg.norm(Q[0])

1.0

In [60]:
#Singular Value Decomposition.
a=np.arange(9).reshape(3,3)+1
U,Sig,VT=np.linalg.svd(a)
print("Sig:",Sig)
U@np.diag(Sig)@VT

Sig: [1.68481034e+01 1.06836951e+00 4.41842475e-16]


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [67]:
#Matrix eigenvalues
#Compute the eigenvalues and right eigenvectors of a square array.
E,V=np.linalg.eig(a)
print("E=",E)
print("V=",V)

E= [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
V= [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
#Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.
np.linalg.eigh(a[, UPLO])

In [64]:
#Compute the eigenvalues of a general matrix.
np.linalg.eigvals(a)

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
#Compute the eigenvalues of a complex Hermitian or real symmetric matrix.
np.linalg.eigvalsh(a[, UPLO])

In [ ]:
#Norms and other numbers

In [ ]:
#Matrix or vector norm.
np.linalg.norm(x[, ord, axis, keepdims])

In [ ]:
#Compute the condition number of a matrix.
np.linalg.cond(x[, p])

In [68]:
#Compute the determinant of an array.
np.linalg.det(a)

0.0

In [69]:
#Return matrix rank of array using SVD method
np.linalg.matrix_rank(a)

NameError: name 'linalg' is not defined

In [72]:
#Compute the sign and (natural) logarithm of the determinant of an array.
np.linalg.slogdet(a)

(0.0, -inf)

In [70]:
#Return the sum along diagonals of the array.
np.trace(a)

15

In [1]:
#Solving equations and inverting matrices

In [2]:
#Solve a linear matrix equation, or system of linear scalar equations.
linalg.solve(a, b)

NameError: name 'linalg' is not defined

In [ ]:
#Solve the tensor equation a x = b for x.
linalg.tensorsolve(a, b[, axes])

In [ ]:
#Return the least-squares solution to a linear matrix equation.
linalg.lstsq(a, b[, rcond])

In [ ]:
#Compute the (multiplicative) inverse of a matrix.
linalg.inv(a)

In [ ]:
#Compute the (Moore-Penrose) pseudo-inverse of a matrix.
linalg.pinv(a[, rcond, hermitian])

In [ ]:
#Compute the ‘inverse’ of an N-dimensional array.
linalg.tensorinv(a[, ind])

In [ ]:
#Compute tensor dot product along specified axes.
tensordot(a, b[, axes])

In [ ]:
#Evaluates the Einstein summation convention on the operands.
einsum(subscripts, *operands[, out, dtype, …])

In [ ]:
#Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.
einsum_path(subscripts, *operands[, optimize])