# Getting Started with pandas

**Highly Recomanded Book for Reference**

<img src="PythonBook.jpg">

In [1]:
import numpy as np

In [43]:
import pandas as pd
from icecream import ic

## Introduction to Pandas Data Structures

### Series
A Series is a one-dimensional array-like object containing a sequence of values (of
similar types to NumPy types) and an associated array of data labels, called its index.
The simplest Series is formed from only an array of data:

In [55]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [52]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [53]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [54]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2['a']

-5

In [57]:
obj2[1]

7

Using NumPy functions or NumPy-like operations, such as filtering with a boolean
array, scalar multiplication, or applying math functions, will preserve the index-value
link:

In [59]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [60]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [63]:
F1=pd.Series([1,2,3],index=["a","b","c"])
F2=pd.Series([2,3,4],index=["a","b","d"])

In [69]:
F3=F1+F2
F3

a    3.0
b    5.0
c    NaN
d    NaN
dtype: float64

In [72]:
F4=F3.isnull()
F4.count()

4

Another way to think about a Series is as a fixed-length, ordered dict, as it is a map‐
ping of index values to data values.

In [10]:
'b' in obj2

True

### Creating Series from Dictionary

In [88]:
sdata = {'Ohio': 35000, 
         'Texas': 71000, 
         'Oregon': 16000, 
         'Utah': 5000,
        'India': np.nan}
obj3 = pd.Series(sdata)
obj3

Ohio      35000.0
Texas     71000.0
Oregon    16000.0
Utah       5000.0
India         NaN
dtype: float64

In [86]:
obj3.index

Index(['Ohio', 'Texas', 'Oregon', 'Utah', 'India'], dtype='object')

In [87]:
obj3.values

array([35000., 71000., 16000.,  5000.,    nan])

In [89]:
sindex=['Oregon', 'Utah','India','Ohio', 'Texas']   #Index Sequence Changed, Observe the mssing value
obj4=pd.Series(sdata,index=sindex)
obj4

Oregon    16000.0
Utah       5000.0
India         NaN
Ohio      35000.0
Texas     71000.0
dtype: float64

### Creating Series from Lists

In [13]:
tdata=[12,14,16]
tind=["a","b","c"]
obj5=pd.Series(tdata,index=tind)
obj5

a    12
b    14
c    16
dtype: int64

In [14]:
obj6=pd.Series({"a":23,"b":34,"c":45,"d":34})
obj6

a    23
b    34
c    45
d    34
dtype: int64

In [15]:
obj5+obj6

a    35.0
b    48.0
c    61.0
d     NaN
dtype: float64

In [16]:
obj6-obj5

a    11.0
b    20.0
c    29.0
d     NaN
dtype: float64

## DataFrame
A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.). The DataFrame has both a row and column index; it can be thought of
as a dict of Series all sharing the same index. 

In [90]:
# Constructing Data Frame using Dictionary

data = {'State': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'Year': [2000, 2001, 2002, 2001, 2002, 2003],
        'Pop': [1.5, 1.7, np.nan, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

State  Year  Pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  NaN
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
# head method selects only the first five rows:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [92]:
# Rearrangement of Columns
pd.DataFrame(data, columns=['State', 'Pop','Year'])

State  Pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  NaN
3  Nevada  2.4
4  Nevada  2.9
5  Nevada  3.2

In [99]:
# If you pass a column that isn’t contained in the dict, it will appear with missing values in the result:
frame4=pd.DataFrame(data, columns=['Year', 'State', 'Pop',"Extra"])

In [106]:
frame4["Extra"]=pd.Series([1,2,3,4,5,6],index=[2,3,1,0,4,5])
frame4

Year   State  Pop  Extra
0  2000    Ohio  1.5      4
1  2001    Ohio  1.7      3
2  2002    Ohio  NaN      1
3  2001  Nevada  2.4      2
4  2002  Nevada  2.9      5
5  2003  Nevada  3.2      6

In [108]:
frame4.columns

Index(['Year', 'State', 'Pop', 'Extra'], dtype='object')

In [112]:
frame4.index=["a","b","c","d","e","f"]
frame4

Year   State  Pop  Extra
a  2000    Ohio  1.5      4
b  2001    Ohio  1.7      3
c  2002    Ohio  NaN      1
d  2001  Nevada  2.4      2
e  2002  Nevada  2.9      5
f  2003  Nevada  3.2      6

In [118]:
# index assignment
frame2=pd.DataFrame(data, columns=['Year', 'State', 'Pop'],index=["a","b","c","d","e","f"])
frame2

Year   State  Pop
a  2000    Ohio  1.5
b  2001    Ohio  1.7
c  2002    Ohio  NaN
d  2001  Nevada  2.4
e  2002  Nevada  2.9
f  2003  Nevada  3.2

In [128]:
frame2.iloc[2,1]

'Ohio'

In [126]:
# Accessing Particular Column
frame2['State']

a      Ohio
b      Ohio
c      Ohio
d    Nevada
e    Nevada
f    Nevada
Name: State, dtype: object

In [113]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [130]:
# Accessing Particular Column using dot operator
frame2.State

a      Ohio
b      Ohio
c      Ohio
d    Nevada
e    Nevada
f    Nevada
Name: State, dtype: object

In [25]:
set(frame2['state'])

{'Nevada', 'Ohio'}

In [131]:
frame3=pd.DataFrame(data, columns=['Year', 'State', 'Pop',"Extra"])
frame3["Extra"]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: Extra, dtype: object

In [136]:
# When you are assigning lists or arrays to a column, the value’s length must match the length of the DataFrame. 
frame3["Extra"]=np.random.randn(6)
frame3

Year   State  Pop     Extra
0  2000    Ohio  1.5 -1.474477
1  2001    Ohio  1.7 -0.538884
2  2002    Ohio  NaN  0.610497
3  2001  Nevada  2.4 -0.376631
4  2002  Nevada  2.9  1.448943
5  2003  Nevada  3.2  2.393023

In [28]:
# If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values in any holes:
val = pd.Series([-1.2, -1.5, -1.7], index=[0,2,4])
frame3["Extra"]=val
frame3

year   state  pop  Extra
0  2000    Ohio  1.5   -1.2
1  2001    Ohio  1.7    NaN
2  2002    Ohio  3.6   -1.5
3  2001  Nevada  2.4    NaN
4  2002  Nevada  2.9   -1.7
5  2003  Nevada  3.2    NaN

In [29]:
del frame3['Extra']
frame3

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
# nested dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame4=pd.DataFrame(pop)

# Outer dict keys as the columns and the inner keys as the row indices

frame4

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [31]:
# transpose the DataFrame
frame4.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [32]:
frame4

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [33]:
frame4.index=[2001, 2002, 2003]

In [34]:
frame4

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   1.5

Reindexing
An important method on pandas objects is reindex, which means to create a new
object with the data conformed to a new index.

In [35]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [137]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [39]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [140]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [139]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [148]:
data=np.arange(16).reshape(4,4)

In [149]:
data[1]

array([4, 5, 6, 7])

In [153]:
frame6=pd.DataFrame(data,index=list(data[:,1]))
frame6

0   1   2   3
1    0   1   2   3
5    4   5   6   7
9    8   9  10  11
13  12  13  14  15

In [147]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])