# Numpy

The NumPy library is the core library for scientific computing in 
Python. It provides a high-performance multidimensional array 
object, and tools for working with these arrays.

In [1]:
#import numpy
import numpy as np

## Creating Arrays

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float) 
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [5]:
#Create an array of zeros
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [7]:
#Create an array of ones
# np.ones((2,3,4),dtype=np.int16) 
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
#Create an array of evenly spaced values (step value) 
d=np.arange(10,25,5) 
d

array([10, 15, 20])

In [9]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,2,5) 

array([0. , 0.5, 1. , 1.5, 2. ])

In [10]:
# Create a constant array 
e=np.full((2,2),7) 
e

array([[7, 7],
       [7, 7]])

In [11]:
7*np.ones((2,2))

array([[7., 7.],
       [7., 7.]])

In [12]:
# Create a 2X2 identity matrix
f=np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random((3,5)) #Create an array with random values

array([[0.30488089, 0.09242655, 0.76829086, 0.12296965, 0.89252594],
       [0.10963581, 0.67911938, 0.41445719, 0.02095587, 0.32679976],
       [0.12313637, 0.63996376, 0.38773047, 0.90818612, 0.71337782]])

## Inspecting Array

In [14]:
# Array dimensions
c.shape

(2, 2, 3)

In [15]:
# Length of array
len(c) 

2

In [16]:
#Number of array dimensions 
print(a.shape,"\t\t",a.ndim)
print(b.shape,"\t\t",b.ndim)
print(c.shape,"\t",c.ndim)

(3,) 		 1
(2, 3) 		 2
(2, 2, 3) 	 3


In [17]:
#Number of array elements
c.size

12

In [18]:
#Data type of array elements
b.dtype 

dtype('float64')

In [19]:
print(type(np.full((2,2),3)))
print(np.full((2,2),3).dtype)

<class 'numpy.ndarray'>
int32


In [20]:
#Name of data type 
b.dtype.name 

'float64'

In [21]:
#Convert an array to a different type
b.astype(int) 

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b.astype(int).astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
int(3.53)

3

In [26]:
float(6) # Typecast

6.0

## Arithmatic Operations

In [27]:
a1=[1,2,3]
b1=[0,1,1]
# c1=a1-b1  # unsupported operand type(s) for -: 'list' and 'list'

In [28]:
#Subtraction
g = a - b 
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [29]:
# Addition
b + a
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [30]:
# Division
print(a / b)
np.divide(a,b)

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [31]:
# Multiplication
a * b
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [32]:
# Exponentiation
print(b)
np.exp(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [33]:
# Square root
np.sqrt(b) 

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
# Print sines of an array
np.sin(a) 

array([0.84147098, 0.90929743, 0.14112001])

In [35]:
# Element-wise cosine 
np.cos(b) 

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [36]:
# Element-wise natural logarithm
np.log(a)  

array([0.        , 0.69314718, 1.09861229])

In [37]:
# Dot product
g=np.array([(1,2),(3,4)])
h=np.array([(2,1),(4,2)])
print(g)
print(h)
g.dot(h)

[[1 2]
 [3 4]]
[[2 1]
 [4 2]]


array([[10,  5],
       [22, 11]])

## Comparison

In [38]:
# Element-wise comparison
print(a)
print(b)
a == b

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[False,  True,  True],
       [False, False, False]])

In [39]:
b < 2

array([[ True, False, False],
       [False, False, False]])

In [40]:
np.array_equal(a, b)

False

## Aggregate Functions

In [41]:
#Array-wise sum
a.sum() 

6

In [42]:
#Array-wise minimum value
a.min() 

1

In [43]:
#Maximum value of an array row 
print(b)
print(b.max())
print("Column wise max:",b.max(axis=0)) 
print("Row wise max:",b.max(axis=1)) 

[[1.5 2.  3. ]
 [4.  5.  6. ]]
6.0
Column wise max: [4. 5. 6.]
Row wise max: [3. 6.]


In [44]:
#Cumulative sum of the elements
b.cumsum(axis=1) 

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [45]:
#Mean
b.mean(axis=0) 

array([2.75, 3.5 , 4.5 ])

In [46]:
#Median 
# b.median() # 'numpy.ndarray' object has no attribute 'median'

In [47]:
#Correlation coefficient
# b.corrcoef() # 'numpy.ndarray' object has no attribute 'corrcoef'

In [48]:
#Standard deviation
np.std(b)

1.5920810978785667

## Copying Arrays 

In [49]:
#Create a view of the array with the same data
h = a.view()
h

array([1, 2, 3])

In [50]:
a

array([1, 2, 3])

In [51]:
# Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [52]:
# Create a deep copy of the array
h = a.copy()
h

array([1, 2, 3])

In [53]:
# Sort an array
a.sort() 
a

array([1, 2, 3])

In [54]:
# Sort the elements of an array's axis
a=np.array([3,2,1])
a.sort(axis=0) 
a

array([1, 2, 3])

## Subsetting, Slicing, Indexing

In [55]:
## Subsetting
#Select the element at the 2nd index 3
a[2] 

3

In [56]:
#Select the element at row 1 column 2
b[1,2] # (equivalent to b[1][2])

6.0

In [57]:
## Slicing
# Select items at index 0 and 1
a[0:2] 

array([1, 2])

In [58]:
# Select items at rows 0 and 1 in column 1
b[0:2,1] 

array([2., 5.])

In [59]:
#Select all items at row 0
b[:1]  #(equivalent to b[0:1, :])
c[1,...] # Same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [60]:
#Reversed array a array([3, 2, 1])
print(a)
a[ : :-1] 

[1 2 3]


array([3, 2, 1])

## Boolean Indexing

In [61]:
#Select elements from a less than 2
a[a<2] 

array([1])

In [62]:
## Fancy Indexing
# Select elements (1,0),(0,1),(1,2) and (0,0)
print(b)
b[[1, 0, 1, 0],[0, 1, 2, 0]] 

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([4. , 2. , 6. , 1.5])

In [63]:
# Select a subset of the matrix’s rows
b[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [64]:
b=np.arange(6).reshape(2,3)+1

In [65]:
# Transposing Array
i = np.transpose(b) # Permute array dimensions
i.T # Permute array dimensions

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# Changing Array Shape
b.ravel() # Flatten the array

array([1, 2, 3, 4, 5, 6])

In [76]:
b.reshape(3,2) # Reshape, but don’t change data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
#  Adding/Removing Elements
b.resize((3,2)) # Return a new array with shape (2,6)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
b.resize((2,3)) # Return a new array with shape (2,6)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a

array([1, 2, 3])

In [83]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# Append items to an array
np.append(a,b) 

array([1, 2, 3, 1, 2, 3, 4, 5, 6])

In [86]:
# Insert items in an array
np.insert(a, 2, 5) # inserts 5 at position 2.

array([1, 2, 5, 3])

In [87]:
np.delete(a,[1]) #Delete items from an array

array([1, 3])

In [ ]:
#  Combining Arrays

In [89]:
# Concatenate arrays

array([10, 15, 20])

In [91]:
print("a: ",a)
print("d: ",d)
np.concatenate((a,d),axis=0) # Concatenate arrays

a:  [1 2 3]
d:  [10 15 20]


array([ 1,  2,  3, 10, 15, 20])

In [92]:
# Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [99]:
e=np.arange(6).reshape(2,3)+7
print('b: \n',b)
print('e: \n',e)
np.r_[b,e] # Stack arrays vertically (row-wise)

b: 
 [[1 2 3]
 [4 5 6]]
e: 
 [[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [100]:
# Stack arrays horizontally (column-wise)
np.hstack((b,e))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [101]:
# Create stacked column-wise arrays
np.column_stack((b,e)) 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [103]:
# Create stacked column-wise arrays
np.c_[b,e] 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [104]:
# Splitting Arrays
np.hsplit(a,3) # Split the array horizontally at the 3rd 

[array([1]), array([2]), array([3])]

In [105]:
np.vsplit(c,2) # Split the array vertically at the 2nd index

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]