# Finding G inverse of given matrix.

In [2]:
import numpy as np     #package required for finding G inverse

A=np.array([[2.5,0.58,0.4],[0.6,0.32,1],[0.2,0.84,4]])
print("A\n" ,A)

r=np.linalg.matrix_rank(A)           #Finding rank of A
print("r\n",r)
size=np.shape(A)                     #size of A
                                    
print("size\n",size)
m=size[0]
n=size[1]

G=np.zeros((m,n))                    # matrix G
print("G\n",G)

B=A[np.ix_([0,r],[0,r])]             # matrix B
print("B\n",B)

r1=np.linalg.matrix_rank(B)          # rank of B
print("r1\n",r1)
if r1==r:
    G[np.ix_([0,r],[0,r])]=np.linalg.inv(B.T)
    G=G.T
    print("The G inverse of given matrix is\n",G)
 

 # Properties of G:
print("AGA\n",A.dot(G).dot(A))             # AGA=A

print("trace of AG",np.trace(A.dot(G)))    #trace(AG)=trace(GA)=rank(A)
print("trace of GA",np.trace(G.dot(A)))
print(r)      

A
 [[2.5  0.58 0.4 ]
 [0.6  0.32 1.  ]
 [0.2  0.84 4.  ]]
r
 2
size
 (3, 3)
G
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
B
 [[2.5 0.4]
 [0.2 4. ]]
r1
 2
The G inverse of given matrix is
 [[ 0.40322581  0.         -0.04032258]
 [ 0.          0.          0.        ]
 [-0.02016129  0.          0.25201613]]
AGA
 [[2.5  0.58 0.4 ]
 [0.6  0.32 1.  ]
 [0.2  0.84 4.  ]]
trace of AG 2.0
trace of GA 2.0
2
