# Group no.5 

   ## Damini Badgujar
   ## Chinmay patil
   ## Tejas Jadhav
   ## Manish Hire

# Aim 1 : To check the definiteness of the given quadratic form

In [7]:


print("Part 1 : To check the definiteness of the given quadratic form ")

print("\nThe given Quadratic form is Q(x)= x'Ax =(x1)^2+(9*x2)^2+(15*x3)^2+(4*x1x2)-(6*x1x3)-(4*x2x3)")


import numpy as np                          


A = np.mat("1 2 -3 ; 2 9 -2 ; -3 -2 15 ")    


print("\n matrix  form of given quadratic form is ")  


print("A : \n\n",A)


e = np.linalg.eigvals(A)


print("\n\nThe eigen values of matrix A are : \n\n ", e)



if all(e)> 0:
    print("\n The given quadratic form is positive definite")
elif all(e)>= 0:
    print("\n The given quadratic form is positive semi definite")
elif all(e)< 0:
    print("\n The given quadratic form is negative definite")
elif all(e)<= 0:
    print("\n The given quadratic form is negative semi definite")
else : 
    print("\n The given quadratic form is indefinite") 
    

Part 1 : To check the definiteness of the given quadratic form 

The given Quadratic form is Q(x)= x'Ax =(x1)^2+(9*x2)^2+(15*x3)^2+(4*x1x2)-(6*x1x3)-(4*x2x3)

 matrix  form of given quadratic form is 
A : 

 [[ 1  2 -3]
 [ 2  9 -2]
 [-3 -2 15]]


The eigen values of matrix A are : 

  [ 0.10035761 16.38643349  8.5132089 ]

 The given quadratic form is positive definite


# Aim 2 : To obtain maxima and minima of the given Quadratric form over normed   vector


In [2]:


print("\n\nPart 2 : To obtain maxima and minima of the given Quadratric form over normed vector ")


print("\n\nThe given Quadratic form is Q(x)= x'Ax =(x1)^2+(9*x2)^2+(15*x3)^2+(4*x1x2)-(6*x1x3)-(4*x2x3)")

l1=max(e)
l2=min(e)

print("\n\nmaxima and minima of the given Quadratric form over normed vector are as follows :") 

print("\n 1. maxima of quadratic form x'Ax over a normed vector is :",l1)

print("\n 2. minima of quadratic form x'Ax over a normed vector is :",l2)



Part 2 : To obtain maxima and minima of the given Quadratric form over normed vector 


The given Quadratic form is Q(x)= x'Ax =(x1)^2+(9*x2)^2+(15*x3)^2+(4*x1x2)-(6*x1x3)-(4*x2x3)


maxima and minima of the given Quadratric form over normed vector are as follows :

 1. maxima of quadratic form x'Ax over a normed vector is : 16.386433492269735

 2. minima of quadratic form x'Ax over a normed vector is : 0.10035760898119861


# Aim 3 : To obtain maxima and minima of the ratio of two Quadratric forms over normed vector

In [3]:


print("\n\npart 3 : To obtain maxima and minima of the ratio of two Quadratric forms over normed vector")

print("\n\n Suppose we have two quadratic forms such that ")
print("\nFirst quadratic form is Q1(x)=x'Ax=(2x1)^2-(14x2)^2-(7x3)^2+(20x1x2)-(12x1x3)+(20x2x3)")
print("\nSecond quadratic form is Q2(x)=x'Bx=(6x1)^2+(17x2)^2+(6x3)^2+(6x1x2)-(2x1x3)-(20x2x3)")      



A = np.mat("2 10 -6 ; 10 -14 10 ; -6 10 -7 ")

print("\n matrix  form of first quadratic form is ")  

print("A : \n\n",A)

B = np.mat("6 3 -1 ; 3 17 -10 ; -1 -10 6")

print("\n matrix  form of second quadratic form is ")  


print("B : \n\n",B)
 
z=np.linalg.inv(B)

print("\n\nThe inverse of matrix B is  :\n\n",z)


print("\n The matrix M is obtained by premultiplying B-inverse to matrix A ") 

M=np.dot(z,A)   

print("M : \n\n",M)



e1 = np.linalg.eigvals(M)


print("\n\nThe eigen values of matrix M are : \n\n ", e1)

l3=max(e1)
newl3=np.round(l3)
l4=min(e1)
newl4=np.round(l4)

print("\n 1. maxima of ratio of two quadratic forms x'Ax & x'Bx over a normed vector is :",newl3)

print("\n 2. minima of ratio of two quadratic forms x'Ax & x'Bx over a normed vector is  :",newl4)





part 3 : To obtain maxima and minima of the ratio of two Quadratric forms over normed vector


 Suppose we have two quadratic forms such that 

First quadratic form is Q1(x)=x'Ax=(2x1)^2-(14x2)^2-(7x3)^2+(20x1x2)-(12x1x3)+(20x2x3)

Second quadratic form is Q2(x)=x'Bx=(6x1)^2+(17x2)^2+(6x3)^2+(6x1x2)-(2x1x3)-(20x2x3)

 matrix  form of first quadratic form is 
A : 

 [[  2  10  -6]
 [ 10 -14  10]
 [ -6  10  -7]]

 matrix  form of second quadratic form is 
B : 

 [[  6   3  -1]
 [  3  17 -10]
 [ -1 -10   6]]


The inverse of matrix B is  :

 [[  2.  -8. -13.]
 [ -8.  35.  57.]
 [-13.  57.  93.]]

 The matrix M is obtained by premultiplying B-inverse to matrix A 
M : 

 [[ 2.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [-8.00000000e+00  4.26325641e-14 -1.00000000e+00]
 [-1.40000000e+01  2.00000000e+00 -3.00000000e+00]]


The eigen values of matrix M are : 

  [-2.00000000e+00  1.00000000e+00  2.56540425e-13]

 1. maxima of ratio of two quadratic forms x'Ax & x'Bx over a normed vector i