# Practical no .2  
## By group no.6 
### Group members  
### 1.Badgujar Shivani Vijay
### 2.Jawdeker Harshada Sharad 
### 3.Patil Nikita Pravin 


# Practical no. 2 solving system of linear equations using Cramer’s rule. 

In linear algebra, Cramer’s rule is an explicit formula for the solution of a system of linear equations with as many equations as unknowns, valid whenever the system has a unique solution. 
Cramer’s Rule is a method that uses determinants to solve systems of equations that have the same number of equations as variables. Consider a system of two linear equations in two variables. If we are solving for x, the x column is replaced with the constant column as x= DX/D and so on for other unknown variables .Where D is the determinant of matrix and Dx is determinant of matrix formed by x column is replaced with the constant column . 


# Problem 1  

In [2]:
import numpy as np 
b=np.array([[-3,17,20]]) 
A=np.array([[2,-1,1],[1,1,-3],[5,-2,-4]]) 
Ax=np.array([[-3,-1,1],[17,1,-3],[20,-2,-4]]) 
Ay=np.array([[2,-3,1],[1,17,-3],[5,20,-4]]) 
Az=np.array([[2,-1,-3],[1,1,17],[5,-2,20]]) 
print("\nThe given matrix A is\n",A) 
print("\nThe given vector b is\n",b) 
p=np.linalg.det(A) 
q=np.linalg.det(Ax) 
r=np.linalg.det(Ay) 
s=np.linalg.det(Az) 
x=q/p 
y=r/p 
z=s/p 
print("\nThe solution of system of linear equation is \n",round(x),round(y),round(z)) 



The given matrix A is
 [[ 2 -1  1]
 [ 1  1 -3]
 [ 5 -2 -4]]

The given vector b is
 [[-3 17 20]]

The solution of system of linear equation is 
 2 3 -4


# Problem 2 

In [4]:
import numpy as np 
M=np.array([[1,0,0,0],[3,2,0,0],[0,1,-1,0],[-2,3,1,3]]) 
print(M)  
a=np.array([2,4,-1,4]) 
b=a.reshape(-1,1) 
print(b)  
s=np.linalg.inv(M) 
print(s) 
x=s@b  
print("\nThe solution of system of linear equation is\n",x) 


[[ 1  0  0  0]
 [ 3  2  0  0]
 [ 0  1 -1  0]
 [-2  3  1  3]]
[[ 2]
 [ 4]
 [-1]
 [ 4]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  3.46944695e-18]
 [-1.50000000e+00  5.00000000e-01  0.00000000e+00 -5.20417043e-18]
 [-1.50000000e+00  5.00000000e-01 -1.00000000e+00  2.25514052e-17]
 [ 2.66666667e+00 -6.66666667e-01  3.33333333e-01  3.33333333e-01]]

The solution of system of linear equation is
 [[ 2.        ]
 [-1.        ]
 [ 0.        ]
 [ 3.66666667]]


 A block matrix or a partitioned matrix is a matrix that is interpreted as having been broken into sections called blocks or submatrices. 
Determinant by using partition method is usually uses when the matrix order is large as it is complicated to find determinant of large order matrix so that’s why when there were no computers  that time peoples  are using these method .But nowadays it very easy to find determinant of large order matrices by using computer. 
Formula if matrix M is partition into A,B,C,D matrices then it’s determinant is  



|M|=|D|*|A-B*Dinv*C|, where D in non-singular 


|M|=|A|*|A-C*Ainv*B|, where A in non-singular 

# Problem 3

In [9]:
import numpy as np 
A=np.array([[1,-2],[2,3]]) 
B=np.array([[5,0],[2,-4]]) 
C=np.array([[1,0],[-1,1]]) 
D=np.array([[0,4],[2,2]]) 
print("\n A\n",A) 
print("\n B\n",B)  
print("\n C\n",C) 
print("\n D\n",D) 
M=np.linalg.det(D) 
m=np.linalg.inv(D) 
q=B@m 
r=q@C 
S=np.linalg.det(A-r) 
Det=M*S 
print ("\n The determinant of a given matrix by partitioning is\n",round(Det)) 



 A
 [[ 1 -2]
 [ 2  3]]

 B
 [[ 5  0]
 [ 2 -4]]

 C
 [[ 1  0]
 [-1  1]]

 D
 [[0 4]
 [2 2]]

 The determinant of a given matrix by partitioning is
 -238


# Problem 4 

In [10]:
import numpy as np 
l=np.array([[1,0,0,0],[2,1,0,0],[-3,-1,1,0],[2,0,2,1]]) 
u=np.array([[2,3,0,0],[0,1,2,0],[0,0,2,1],[0,0,0,3]]) 
c=np.array([[2],[1],[1],[0]]) 
A=l@u 
X=np.linalg.inv(A)@c 
print("\n The solution of given system of linear equations is\n ",X) 



 The solution of given system of linear equations is
  [[ 17.5]
 [-11. ]
 [  4. ]
 [ -4. ]]
