# Q 86) Write a Python class to convert an integer to a roman numeral.

In [2]:
class py_solution:
    def int_to_Roman(self, num):
        val = [
            1000, 900, 500, 400,
            100, 90, 50, 40,
            10, 9, 5, 4,
            1
            ]
        syb = [
            "M", "CM", "D", "CD",
            "C", "XC", "L", "XL",
            "X", "IX", "V", "IV",
            "I"
            ]
        roman_num = ''
        i = 0
        while  num > 0:
            for _ in range(num // val[i]):
                roman_num += syb[i]
                num -= val[i]
            i += 1
        return roman_num

In [3]:
print(py_solution().int_to_Roman(4))
print(py_solution().int_to_Roman(44))

IV
XLIV


# Q 87 Write a Python class named Rectangle constructed by a length and width and a method which will compute the area of a rectangle.

### Algorithm:
#### 1. Take the value of length and breadth from the user.
#### 2. Create a class and using a constructor initialise values of that class.
#### 3. Create a method called as area and return the area of the class.
#### 4. Create an object for the class.
#### 5. Using the object, call the method area() with the parameters as the length and breadth taken from the user.
#### 6. Print the area.
#### 7. Exit

In [4]:
class rectangle():
    def __init__(self,breadth,length):
        self.breadth=breadth
        self.length=length
    def area(self):
        return self.breadth*self.length
a=int(input("Enter length of rectangle: "))
b=int(input("Enter breadth of rectangle: "))
obj=rectangle(a,b)
print("Area of rectangle:",obj.area())
 
print()


Enter length of rectangle: 5
Enter breadth of rectangle: 3
Area of rectangle: 15



# Q 89) How to add a border (filled with 0’s) around an existing two dimensional array?

In [5]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# Q 92) What Advantages Do Numpy Arrays Offer Over (nested) Python Lists?

Python’s lists are efficient general-purpose containers. They support (fairly) efficient insertion, deletion, appending, and concatenation, and Python’s list comprehensions make them easy to construct and manipulate. However, they have certain limitations: they don’t support “vectorized” operations, like elementwise addition and multiplication, and the fact that they can contain objects of differing types mean that Python must store type information for every element, and must execute type-dispatching code when operating on each element. This also means that very few list operations can be carried out by efficient C loops – each iteration would require type checks and other Python API bookkeeping.


# Q 93) Explain all file processing modes supported in Python.

 Python language supports two types of files. First one is text file that store data in the form of text file and readable by human and computer. Second one is binary file that store binary data and readable by computer only. Python has a built-in function open() to open a file. This function returns a file object, also called a handle, as it is used to read or modify the file accordingly.


open(file_name , [access_mode],[buffer_size],[encoding])

The access_mode is an optional string that specifies the mode in which the file is opened. By default, it is set to read-only "r". In this mode, we get data in text form after reading from the file. On the other hand, binary mode returns bytes. It's preferable for accessing the non-text files like an image or the exe files.

Different modes of opening a file are

r - open a file for reading. (default)

w - Open a file for writing. If file already exists its data will be cleared before opening. Otherwise new file will be created

x - open for exclusive creation, failing if the file already exists

a - open for writing, appending to the end of the file if it exists

b - binary mode

t - text mode (default)

+r - Open a file for updating (reading and writing)


# Q 94) Write few NumPy package commands useful for linear algebra with examples

In [6]:
import numpy as np

In [7]:
# we use np.array for creating matrix in python
A=np.array([[8,1,3,16],[0,3,0,-9],[-8,-1,-3,-16]])
print(A)

[[  8   1   3  16]
 [  0   3   0  -9]
 [ -8  -1  -3 -16]]


### Examples
###  i) Cholesky decomposition.

In [8]:
a=np.array([[6,15,55],
            [15,55,225],
            [55,225,979]])
z=np.linalg.cholesky(a)
print(z)

[[ 2.44948974  0.          0.        ]
 [ 6.12372436  4.18330013  0.        ]
 [22.45365598 20.91650066  6.11010093]]


###  ii) for finding rank of matrix

In [9]:
r=np.linalg.matrix_rank(A)
print(r)

2


###   iii) compute eigen values and eigen vector of square array

In [19]:
a=np.array([[6,15,5],[5,6,8],[1,2,3]])
print(a)
e=np.linalg.eigvals(a)
print(e)

[[ 6 15  5]
 [ 5  6  8]
 [ 1  2  3]]
[16.20314318 -2.80774182  1.60459864]


###   iv) for finding determinate

In [20]:
det=np.linalg.det(a)
print(det)

-72.99999999999999


###   v) for matrix multiplication

In [18]:
b=np.array([[6,6], [1,3]])
print('b :\n',b)
c=np.array([[3,4],[6,7]])
print('c : \n',c)
d=np.dot(b,c)
print('Product of the two matrices :\n ',d)

b :
 [[6 6]
 [1 3]]
c : 
 [[3 4]
 [6 7]]
Product of the two matrices :
  [[54 66]
 [21 25]]
