# CHECKING VARIOUS PROPERTIES OF MATRICES


In [2]:
import numpy as np

In [111]:
A=np.array([[4,56,89],[56,5,-9],[89,-9,4]])
print(A)

[[ 4 56 89]
 [56  5 -9]
 [89 -9  4]]


### SIZE OF MATRIX AND CHECK WHETHER GIVEN MATRIX IS SQUARE OR NOT






In [112]:
[m,n]=A.shape
print("\n Size of matrix A is:",A.shape)

if m == n:
    print("\n A is square matrix with dimensions",m,'x',n)
else:
    print("\n A is not square matrix with dimensions",m,'x',n)


 Size of matrix A is: (3, 3)

 A is square matrix with dimensions 3 x 3


### CHECK WHETHER GIVEN MATRIX IS IDEMPOTENT OR NOT



In [99]:
A=np.array([[4,56,89],[56,5,-9],[89,-9,4]])
AA=np.linalg.matrix_power(A,2)

if np.array_equal(A,AA):
    print("matrix is idempotent")

else: 
    print("matrix is not idempotent")

matrix is not idempotent


### TRANSPOSE OF A MATRIX 


        

In [100]:
B=np.array([[4,56,89],[65,5,10],[98,9,4]])
print(B)
print("\n Transpose of matrix B is:","\n",np.transpose(B))

# print("\n Transpose of matrix B is:" , "\n",B.T)


[[ 4 56 89]
 [65  5 10]
 [98  9  4]]

 Transpose of matrix B is: 
 [[ 4 65 98]
 [56  5  9]
 [89 10  4]]


###  CHECK WHETHER GIVEN MATRIX IS SYMMETRIC OR NOT



In [164]:
if np.array_equal(B,B.T):
    print("matrix is symmetric")

else: 
    print("matrix is not symmetric")

matrix is not symmetric


### CHECK WHETHER GIVEN MATRIX IS SINGULAR OR NON-SINGULAR



In [94]:
A=np.array([[4,56,89],[56,5,-9],[89,-9,4]])
det_A=np.linalg.det(A)
print("Determinant of matrix A is:",det_A)

if np.array_equal(det_A,0):
    print("matrix is singular")

else: 
    print("matrix is non-singular")

Determinant of matrix A is: -142105.00000000006
matrix is non-singular


### RANK OF MATRIX

In [95]:
np.linalg.matrix_rank(A)

3

### ORTHOGONALITY OF A MATRIX

In [150]:
I=np.eye(3,3)
print(I)

A=np.array([[4,56,89],[56,5,-9],[89,-9,4]])
print("\n",A)

if det_A != 0:
    print("\n Inverse of matrix A exist.")
else:
    print("\n Inverse of matrix A does not exist.")

    
A_inv=np.linalg.inv(A)
print("\n Inverse of matrix A is:","\n",A_inv)

if np.array_equal(A.T*A,I):
    print("\n Given matrix is orthogonal")
elif np.array_equal(A*A.T,I):
    print("\n Given matrix is orthogonal")
else:
    print("\n Given matrix is not orthogonal")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[ 4 56 89]
 [56  5 -9]
 [89 -9  4]]

 Inverse of matrix A exist.

 Inverse of matrix A is: 
 [[ 0.00042926  0.00721298  0.00667816]
 [ 0.00721298  0.05562788 -0.03532599]
 [ 0.00667816 -0.03532599  0.02192745]]

 Given matrix is not orthogonal


### EIGEN VALUES


In [154]:
E,V=np.linalg.eig(A)
print("E=",E)
print("\n V=",V)



E= [-105.1922449   105.37186251   12.82038239]

 V= [[-0.69350282  0.71968967 -0.03317559]
 [ 0.4013093   0.34764426 -0.84740446]
 [ 0.59833493  0.60099105  0.52991043]]


In [168]:
A_2=A*A
print(A_2)

Values,Vector=np.linalg.eig(A_2)
print("\n Values=",Values)
print("\n Vector=","\n",Vector)


[[  16 3136 7921]
 [3136   25   81]
 [7921   81   16]]

 Values= [ 8563.80353191 -8475.14008693   -31.66344499]

 Vector= 
 [[ 0.70591138  0.70826261  0.00729308]
 [ 0.26548542 -0.25503008 -0.92977263]
 [ 0.65666324 -0.65827329  0.36806203]]


### DEFINITENESS OF A MATRIX

In [169]:
if np.all(E>0):
    print('\n\t The given matrix is positive definite')
elif np.all(E>=0):
    print('\n\t The given matrix is positive semi-definite')
elif np.all(E<0):
    print('\n\t The given matrix is negative definite')
elif np.all(E<=0):
    print('\n\t The given matrix is negative semidefinite')
else:
    print('\n\t The given matrix is indefinite')


	 The given matrix is indefinite


### SKEW SYMMETRIC MATRIX

In [170]:
if np.array_equal(A,-A.T):
    print("A is skew symmetric matrix")
else:
    print("A is not skew symmetric matrix")

A is not skew symmetric matrix


In [179]:
print("Upper triangular matrix is: \n", np.triu(A), "\n")
print("Lower triangular matrix is: \n", np.tril(A), "\n")

Upper triangular matrix is: 
 [[ 4 56 89]
 [ 0  5 -9]
 [ 0  0  4]] 

Lower triangular matrix is: 
 [[ 4  0  0]
 [56  5  0]
 [89 -9  4]] 



### DIAGONAL ELEMENTS OF A MATRIX

In [195]:
A=np.array([[4,56,89],[65,5,-9],[89,10,4]])
print(A)
print("\n Main Diagonal elements:",A.diagonal())
print("\n Diagonal above main Diagonal elements:",np.diag(A, 1))
print("\n Diagonal below main Diagonal elements:",np.diag(A, -1))

[[ 4 56 89]
 [65  5 -9]
 [89 10  4]]

 Main Diagonal elements: [4 5 4]

 Diagonal above main Diagonal elements: [56 -9]

 Diagonal below main Diagonal elements: [65 10]


### FORMATION OF MATRIX USING 

In [7]:
A=np.diag([4,4,4,4,0,0])
print(A)

[[4 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [19]:
data=np.array([6,7,9])
A=np.diag(data, k=3)
A=np.diag([20,-9],k=-4)
print(A)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [20  0  0  0  0  0]
 [ 0 -9  0  0  0  0]]


In [15]:
data=np.array([-10,3,89,2,-8])
np.diag(data,k=1)

array([[  0, -10,   0,   0,   0,   0],
       [  0,   0,   3,   0,   0,   0],
       [  0,   0,   0,  89,   0,   0],
       [  0,   0,   0,   0,   2,   0],
       [  0,   0,   0,   0,   0,  -8],
       [  0,   0,   0,   0,   0,   0]])

In [16]:
data=np.array([9,100,-20,80])
np.diag(data,k=2)

array([[  0,   0,   9,   0,   0,   0],
       [  0,   0,   0, 100,   0,   0],
       [  0,   0,   0,   0, -20,   0],
       [  0,   0,   0,   0,   0,  80],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0]])