# Topic : Gram-Schmidt Orthonormalization/Orthogonalisation


# Group No.-14

## Author :
### 1.Shah Puja 
### 2.Patil Priyanka
### 3.Patil Sharda
### 4.Patil Gayatri 

### Q. Let X1=(1,0,1,1)' ,X2=(-1,0,-1,1)' ,X3=(0,-1,1,1)' and X4=(0,0,1,0)' are linearly independent set of vectors of                       R^4.Find an Orthonormal basis of R^4 starting with {X1,X2,X3,X4}

In [12]:
import numpy as np
A=np.matrix([1,-1,0,0,0,0,-1,0,1,-1,1,1,1,1,1,0]).reshape(4,4)
A

matrix([[ 1, -1,  0,  0],
        [ 0,  0, -1,  0],
        [ 1, -1,  1,  1],
        [ 1,  1,  1,  0]])

In [13]:
# size of matrix A
print(A.shape)
print(np.linalg.det(A))         # To check matrix a is nonsigular or not

(4, 4)
-2.0


In [14]:
X=A[:,0]                      # 1st column of matrix A
B=(X/np.linalg.norm(X))       # norm of vector x i.e ||x||=(1^2+1^2+1^2)^(0.5)
B                          # 1st column of orthonormal matrix


matrix([[0.57735027],
        [0.        ],
        [0.57735027],
        [0.57735027]])

In [15]:
# TO find other columns of orthonormal matrix
#formula for Gramm-schmidt orthogonal matrix Zk=Xk-sum(<Xk,Zj>/<Zj,Zj>)*Zj  j=1:k-1,k=1:n
for i in range(1,3):
    z1=np.zeros((4,1)).reshape(4,1)
    for j in range(0,i-1):
        p=np.divide(np.vdot(A[:,i],B[:,j]),np.vdot(B[:,j],B[:,j])) * B[:,j]
        z1=np.add(z1,p)
    
    B[:,i]=np.subtract(A[:,i],z1)
    B[:,i]=np.divide(B[:,i],np.linalg.norm(B[:,i]))
print("The given matrix is :",A)
print("The orthonormalised matrix is :",B)

                     




IndexError: index 1 is out of bounds for axis 1 with size 1

###  Q. For any x vector belongs to R^n(n>=1),verify that I-(2xx')/(x'x) is an orthogonal matrix or not

In [16]:
C=np.random.randint(1,5,size=(3,1))
C

array([[3],
       [2],
       [4]])

In [17]:
I=np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
t2=np.matmul(C,np.transpose(C))
t3=np.matmul(np.transpose(C),C)
t5=(2*t2)/t3
matrix=np.subtract(I,t5)
print(matrix)

[[ 0.37931034 -0.4137931  -0.82758621]
 [-0.4137931   0.72413793 -0.55172414]
 [-0.82758621 -0.55172414 -0.10344828]]


In [19]:
matrix1=np.vdot(matrix,matrix)

if(matrix1==0):
    print("The given matrix is orthogonal :   ",    matrix)
else:
    print("The given matrix is not orthogonal:   ",   matrix )


The given matrix is not orthogonal:    [[ 0.37931034 -0.4137931  -0.82758621]
 [-0.4137931   0.72413793 -0.55172414]
 [-0.82758621 -0.55172414 -0.10344828]]
