# Introduction To Python Software:
    Assignment 
    1.Asavari Deshmukh
    2.Geetanjali Malpure
    3.Sneha Mahale
    4.Dinesh Jathar
    5.Swapnil Rajput

### What is Python Software ?
       Python is a high-level, interpreted, interactive and object-oriented scripting language. Python is designed to be           highly  readable. It uses English keywords frequently whereas the other languages use punctuations. It has fewer        syntactical constructions than other languages.

### History of Python:
    Python was developed by Guido van Rossum in the late eighties and early nineties at the National Research Institute for Mathematics and Computer Science in the Netherlands.

    1. Python is derived from many other languages, including ABC, Modula-3, C, C++, Algol-68, SmallTalk, and Unix shell and other scripting languages.
    2. Python is copyrighted. Like Perl, Python source code is now available under the GNU General Public License (GPL).
    3. Python is now maintained by a core development team at the institute, although Guido van Rossum still holds a vital   role in directing its progress.
            

##### Use of '#' in python:
            '#' isused for a comment in python markdown.
            
#####  Command to clear Python Interpreter Console on Window :
Using Python Definition:

import os

def clear(): os.system('cls')       #on Windows System

clear()

### Python IDLE:
        Python IDLE looks very similar to python shell app or command prompt but it has many more functionalities. It comes with very powerful IDLE Editor tool.Python IDLE editor is a very easy to use and convenient for many people because of its GUI, designed as your simple Notepad file.

#### How to run python in IDLE?
    Once you have your program ready, save your program in any directory and execute the program from top bar of window.You can see many options available on top of window as such –File, Edit, Format, Run, Options, Windows, and Help.

    You can run your program by selecting “Run” >> “Run Module” or just press “F5”. The output of your program will appear in the background “Python 3.8 Shell” window.

    If your shell window is not open at that time, then the moment you click on “run module” or press- F5 shell window will automatically open with you program output.

#### Matrix operations on matrices using python:
##### numpy Package- 
    The numpy library is the code library for scientific computing in python. It provide a high performance multi-dimensional array
    object and tools for working with these arrays.

In Python we can solve the different matrix manipulations and operations. Numpy Module provides different methods for matrix operations.

add() − add elements of two matrices.

subtract() − subtract elements of two matrices.

divide() − divide elements of two matrices.

multiply() − multiply elements of two matrices.

dot() − It performs matrix multiplication, does not element wise multiplication.

sqrt() − square root of each element of matrix.

sum(x,axis) − add to all the elements in matrix. Second argument is optional, it is used when we want to compute the column sum if axis is 0 
and row sum if axis is 1.

“T” − It performs transpose of the specified matrix.

In [1]:
#### Example code:
import numpy
##### Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
#####  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))
##### subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))
##### divide()is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))
print ("The product of two matrices : ")
print (numpy.dot(x,y))
print ("square root is : ")
print (numpy.sqrt(x))
print ("The summation of elements : ")
print (numpy.sum(y))
print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))
print ("The row wise summation: ")
print (numpy.sum(y,axis=1))
##### using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Addition of two matrices: 
[[ 8 10]
 [13 15]]
Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]
Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
Multiplication of two matrices: 
[[ 7 16]
 [36 50]]
The product of two matrices : 
[[25 28]
 [73 82]]
square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of elements : 
34
The column wise summation  : 
[16 18]
The row wise summation: 
[15 19]
Matrix transposition : 
[[1 4]
 [2 5]]


##### Determinant and rank of matrix-
        The NumPy library of Python makes it a breeze to evaluate the determinant of a matrix of any order.

We will use the numpy.linalg.det( ) function from the linalg (linear algebra) module of the NumPy library to find the determinant of a matrix.For finding the rank of matrix, we use command rank = numpy.linalg.matrix_rank(a).
***Example-

In [2]:
import numpy as np

A = np.array([[2,-5],[6,7]])
d = np.linalg.det(A)
print('Matrix A:')
print(A)
print('Determinant of Matrix A:')
print(np.around(d, decimals=4))   # Rounding the value
rank = numpy.linalg.matrix_rank(A)
print("Rank of matrix A: ",rank)

Matrix A:
[[ 2 -5]
 [ 6  7]]
Determinant of Matrix A:
44.0
Rank of matrix A:  2


#### Handling various types of file:
    Python provides inbuilt functions for creating, writing and reading files. There are two types of files that can be 
handled in python, normal text files and binary files (written in binary language, 0s and 1s).

1. Text files: In this type of file, Each line of text is terminated with a special character called EOL (End of Line), 
which is the new line character (‘\n’) in python by default.
2. Binary files: In this type of file, there is no terminator for a line and the data is stored after converting it   
into machine-understandable binary language.

***Syntax-
File_object = open(r"File_Name", "Access_Mode")

##### Getting information about various components of Python using help command.

The help() method calls the built-in Python help system.The help() method is used for interactive use. It's recommended 
to try it in your interpreter when you need help to write Python program and use Python modules.

***Syntax-

help(object)

***Example-

help(print)

help(list)

help(dict)


##### Print command in python:
    The print() function prints the specified message to the screen, or other standard output device.

The message can be a string, or any other object, the object will be converted into a string before written to the screen.

***Syntax- 

print(object(s), sep=separator, end=end, file=file, flush=flush)


###### Example-

In [3]:
print("Hello world")
print("Good morning")

Hello world
Good morning


#### Use of various commands related to looping (repetition) such as if, for, while, break:

#####  if statement:
    The IF statement is similar to that of other languages. The if statement contains a logical expression using which the data is compared and a decision is made based on the result of the comparison.
    
***Syntax-
    if expression:
    
         statement(s)
               

#####  if...else statements:
    An else statement can be combined with an if statement. An else statement contains a block of code that executes if the conditional expression in the if statement resolves to 0 or a FALSE value.The else statement is an optional statement and there could be at the most only one else statement following if.
    
***Syntax-
    if expression:
    
      statement(s)
   else:
   
       statement(s)
       

######  The elif Statement:
    The elif statement allows you to check multiple expressions for TRUE and execute a block of code as soon as one of the conditions evaluates to TRUE.Similar to the else, the elif statement is optional. However, unlike else, for which there can be at the most one statement, there can be an arbitrary number of elif statements following an if.

***Syntax-
    if expression1:
    
     statement(s)
elif expression2:

      statement(s)
elif expression3:

     statement(s)
else:

     statement(s)
     
     
######  while Loop Statements:
    A while loop statement in Python programming language repeatedly executes a target statement as long as a given condition is true.

***Syntax-
while expression:

    statement(s)
    
    
#####  for Loop Statements:   
    The for statement in Python has the ability to iterate over the items of any sequence, such as a list or a string.

***Syntax-
for iterating_var in sequence:

    statements(s)
    
##### break statement:
    The most common use of break is when some external condition is triggered requiring a hasty exit from a loop. The break statement can be used in both while and for loops.If you are using nested loops, the break statement stops the execution of the innermost loop and starts executing the next line of the code after the block.
    
***Syntax-
break



 
 ##### Example:
 

In [4]:
##### 1). if - 

var1 = 100
if var1:
 print ("1 - Got a true expression value")
 print (var1)
 
#### 2). if-else - 
amount=int(input("Enter amount: "))
if amount<1000:
 discount=amount*0.05
 print ("Discount",discount)
else:
 discount=amount*0.10
 print ("Discount",discount)
 
print ("Net payable:",amount-discount)

#### 3). if-elif -

amount=int(input("Enter amount: "))
if amount<1000:
 discount=amount*0.05
 print ("Discount",discount)
elif amount<5000:
 discount=amount*0.10
 print ("Discount",discount)
else:
 discount=amount*0.15
 print ("Discount",discount)
print ("Net payable:",amount-discount)

#### 4). while -

count = 0
while (count < 9):
 print ('The count is:', count)
 count = count + 1
print ("Good bye!")

#### 5). for -

for letter in 'Python': # traversal of a string sequence
 print ('Current Letter :', letter)
print()
fruits = ['banana', 'apple', 'mango']
for fruit in fruits: # traversal of List sequence
 print ('Current fruit :', fruit)
print ("Good bye!")

#### 6). break -

no=int(input('any number: '))
numbers=[11,33,55,39,55,75,37,21,23,41,13]
for num in numbers:
 if num==no:
    print ('number found in list')
    break
else:
    print ('number not found in list')


1 - Got a true expression value
100
Enter amount: 56
Discount 2.8000000000000003
Net payable: 53.2
Enter amount: 89
Discount 4.45
Net payable: 84.55
The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8
Good bye!
Current Letter : P
Current Letter : y
Current Letter : t
Current Letter : h
Current Letter : o
Current Letter : n

Current fruit : banana
Current fruit : apple
Current fruit : mango
Good bye!
any number: 33
number found in list


### Various functions in statistics toolbox in Python:

#### Averages and measures of central location.
    These functions calculate an average or typical value from a population or sample.
    
    
    
    

In [5]:
import module
from tabulate import tabulate
  
mydata =[{"mean()","Arithmetic mean (“average”) of data"},
         {"fmean()","Fast, floating point arithmetic mean"},
          {"geometric_mean()","Geometric mean of data"},
           {"harmonic_mean()","Harmonic mean of data"},
            {"median()","Median (middle value) of data"},
             {"median_low()","Low median of data"},
              {"median_high()","High median of data"},
               {"median_grouped()","Median, or 50th percentile, of grouped data"},
                 {"mode()","Single mode (most common value) of discrete or nominal data"},
                   {"multimode()","List of modes (most common values) of discrete or nomimal data"},
                     {"quantiles()","Divide data into intervals with equal probability"}]

head=["Function","Use"]
print(tabulate(mydata, headers=head, tablefmt="grid"))


Hey! Looks like you accidentally pulled in an incorrect dependency. This can bork your software supply chain in all sorts of ways, so it's very important to be careful with what you're pulling in. Read more about software supply chain security here: https://www.usenix.org/conference/usenixsecurity19/presentation/torres-arias
+----------------------------------------------------------------+-------------------------------------------------------------+
| Function                                                       | Use                                                         |
+================================================================+=============================================================+
| mean()                                                         | Arithmetic mean (“average”) of data                         |
+----------------------------------------------------------------+-------------------------------------------------------------+
| fmean()                   

#### Measures of spread:
    These functions calculate a measure of how much the population or sample tends to deviate from the typical or average values.

In [6]:

mydata=[{"pstdev()","Population standard deviation of data"},
          {"pvariance()","Population variance of data"},
            {"stdev()","Sample standard deviation of data"},
              {"variance()","Sample variance of data"}]
head=["Function","Use"]
print(tabulate(mydata,headers=head,tablefmt="grid"))

+-----------------------------------+---------------------------------------+
| Function                          | Use                                   |
+===================================+=======================================+
| pstdev()                          | Population standard deviation of data |
+-----------------------------------+---------------------------------------+
| pvariance()                       | Population variance of data           |
+-----------------------------------+---------------------------------------+
| Sample standard deviation of data | stdev()                               |
+-----------------------------------+---------------------------------------+
| Sample variance of data           | variance()                            |
+-----------------------------------+---------------------------------------+


#### Various basic mathematical operators and inbuilt functions:

In [9]:

from prettytable import PrettyTable 

myTable = PrettyTable(["Sr no.","Function","Description"]) 
  
myTable.add_row(["1","ceil(x)","Return the Ceiling value. It is the smallest integer, greater or equal to the number x"]) 
myTable.add_row(["2","copysign(x, y)","It returns the number x and copy the sign of y to x"]) 
myTable.add_row(["3","fabs(x)","Returns the absolute value of x"]) 
myTable.add_row(["4","factorial(x)","Returns factorial of x. where x ≥ 0"]) 
myTable.add_row(["5","floor(x)","Return the Floor value. It is the largest integer, less or equal to the number x"]) 
myTable.add_row(["6","fsum(iterable)","Find sum of the elements in an iterable object"]) 
myTable.add_row(["7","gcd(x, y)","Returns the Greatest Common Divisor of x and y"]) 
myTable.add_row(["8","isfinite(x)","Checks whether x is neither an infinity nor nan"]) 
myTable.add_row(["9","isinf(x)","Checks whether x is infinity"]) 
myTable.add_row(["10","isnan(x)","Checks whether x is not a number"]) 
myTable.add_row(["11","remainder(x, y)","Find remainder after dividing x by y"]) 

print(myTable)

+--------+-----------------+----------------------------------------------------------------------------------------+
| Sr no. |     Function    |                                      Description                                       |
+--------+-----------------+----------------------------------------------------------------------------------------+
|   1    |     ceil(x)     | Return the Ceiling value. It is the smallest integer, greater or equal to the number x |
|   2    |  copysign(x, y) |                  It returns the number x and copy the sign of y to x                   |
|   3    |     fabs(x)     |                            Returns the absolute value of x                             |
|   4    |   factorial(x)  |                          Returns factorial of x. where x ≥ 0                           |
|   5    |     floor(x)    |    Return the Floor value. It is the largest integer, less or equal to the number x    |
|   6    |  fsum(iterable) |                     Find su