# Solving System of Linear Equations

## Assignment 1 
### by Group 4
#### Shubham Shende , Sham Patil , Shivani Dhangar

## Problem 1

In [1]:
import numpy as np
A = np.matrix([[2,1,2,1,-1],
               [0,0,1,1,-3],
               [1,0,0,-2,1],
               [2,0,2,0,-1],
               [3,0,4,10,-2],
               [-1,0,0,10,0]])
print("A\n",A)
b=np.matrix([[-10],[3],[1],[-1],[5],[7]])
print("b\n",b)

A
 [[ 2  1  2  1 -1]
 [ 0  0  1  1 -3]
 [ 1  0  0 -2  1]
 [ 2  0  2  0 -1]
 [ 3  0  4 10 -2]
 [-1  0  0 10  0]]
b
 [[-10]
 [  3]
 [  1]
 [ -1]
 [  5]
 [  7]]


if matrix is full column rank matrix then sythem of linear equation has a one perticular solution & if matrix is not full column rank matrix then sythem of linear equation has a infinitely many solution.

In [2]:
r= np.linalg.matrix_rank(A)
print("r\n" ,r)

r
 5


it is singular matrix. There exist generlized inverse of matrix A.

In [3]:
size=np.shape(A)                                   #size (Dimension) of A
print("size\n",size)
m=size[0]
n=size[1]

G=np.zeros((m,n))                                  #creating zeros  matrix G of order(m,n)
print("G\n",G)
  
B=A[np.ix_([0,1,2,3,r],[0,1,2,3,r-1])]             # choosing  matrix B such thant rank of B is equal to r
print("B\n",B)

rB=np.linalg.matrix_rank(B)                        # rank of B
print("rB\n",rB)
if rB==r:
    G[np.ix_([0,1,2,3,r],[0,1,2,3,r-1])]=np.linalg.inv(B.T)
    G=G.T
    print("The G inverse of given matrix is\n",np.round(G,4))
 


size
 (6, 5)
G
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
B
 [[ 2  1  2  1 -1]
 [ 0  0  1  1 -3]
 [ 1  0  0 -2  1]
 [ 2  0  2  0 -1]
 [-1  0  0 10  0]]
rB
 5
The G inverse of given matrix is
 [[ 0.      0.9091  2.2727 -0.4545  0.      0.3636]
 [ 1.     -0.0909 -0.2273 -0.9545  0.     -0.1364]
 [ 0.     -1.2727 -2.6818  1.1364  0.     -0.4091]
 [ 0.      0.0909  0.2273 -0.0455  0.      0.1364]
 [ 0.     -0.7273 -0.8182  0.3636  0.     -0.0909]]


solution of system having b vector (coefficient vector) (34 -45 129) is sol=G*b+(I-GA)*Z where z is any random vector

In [4]:
Z1=10*np.random.uniform(size=(5,1))
print("Z1\n",np.round(Z1,2))
Z2=10*np.random.uniform(size=(5,1))
print("Z2\n",np.round(Z2,2))
I=np.eye(n)
print("I\n",I)
sol_1=G*b+(I-G*A)*Z1
sol_2=G*b+(I-G*A)*Z2
print("First solution of given system of linear eqiation having  \n",np.round(sol_1,2))
print("Second solution of given system of linear eqiation having  \n",np.round(sol_2,2))


Z1
 [[6.24]
 [2.26]
 [7.81]
 [8.9 ]
 [7.28]]
Z2
 [[4.37]
 [4.94]
 [9.62]
 [3.89]
 [7.51]]
I
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
First solution of given system of linear eqiation having  
 [[  8. ]
 [-10.5]
 [-10.5]
 [  1.5]
 [ -4. ]]
Second solution of given system of linear eqiation having  
 [[  8. ]
 [-10.5]
 [-10.5]
 [  1.5]
 [ -4. ]]


## problem 2

finding general solution of linear equation of system A x = B

In [5]:
import numpy as np
A = np.matrix([[2,2,0,4],
               [1,0,3,1],
               [6,6,1,8],
              [2,4,5,2]])
print("A\n" ,A)
b=np.matrix([[2],
             [6],
             [12],
             [2]])
print("b\n" ,b)

A
 [[2 2 0 4]
 [1 0 3 1]
 [6 6 1 8]
 [2 4 5 2]]
b
 [[ 2]
 [ 6]
 [12]
 [ 2]]


if matrix is full column rank matrix then sythem of linear equation has a one perticular solution &
if matrix is not full column rank matrix then sythem of linear equation has a infinitely many solution.


In [6]:
rank = np.linalg.matrix_rank(A)
print("rank\n" ,rank)

rank
 4


Given matrix rank is same as number of columns in it,
hence, matrix is FCRM and 
Also it is non singular matrix 
therefore there exist a regular inverse of matrix A.

In [7]:
inv_A=np.linalg.inv(A)
print("inv_A\n" ,inv_A)

inv_A
 [[-1.075  0.35   0.575 -0.325]
 [ 0.025 -0.45  -0.025  0.275]
 [ 0.1    0.2   -0.1    0.1  ]
 [ 0.775  0.05  -0.275  0.025]]


solution of system is x = Inv_A * B

In [8]:
sol=inv_A*b
print("solution of a given syatem of linear equations is\n" ,sol)

solution of a given syatem of linear equations is
 [[ 6.2]
 [-2.4]
 [ 0.4]
 [-1.4]]


## Problem 3

In [9]:
A= np.matrix([[3,5,2,-4,-6],
               [1,2,-4,-6,7],
               [8,3,10,-6,-25]])
print("A\n" ,A)

A
 [[  3   5   2  -4  -6]
 [  1   2  -4  -6   7]
 [  8   3  10  -6 -25]]


if matrix is full column rank matrix then sythem of linear equation has a one perticular solution &
if matrix is not full column rank matrix then sythem of linear equation has a infinitely many solution.

In [10]:
r= np.linalg.matrix_rank(A)
print("r\n" ,r)

r
 3


Given matrix is not FCRM & also it is singular matrix. There exist generlized inverse of matrix A.

In [11]:
size=np.shape(A)                             #size (Dimension) of A
print("size\n",size)
m=size[0]
n=size[1]

G=np.zeros((m,n))                            #Creating a zeros matrix G of order (m,n)
print("G\n",G)

B=A[np.ix_([0,1,r-1],[0,1,r-1])]             # choosing matrix B such that its has rank equal to r
print("B\n",B)
rB= np.linalg.matrix_rank(B)
print("rB\n" ,rB)

if rB==r:                                                                
    G[np.ix_([0,1,r-1],[0,1,r-1])]=np.linalg.inv(B.T)
    G=(G.T)
    print("The G inverse of given matrix is\n",G)

size
 (3, 5)
G
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
B
 [[ 3  5  2]
 [ 1  2 -4]
 [ 8  3 10]]
rB
 3
The G inverse of given matrix is
 [[-0.22857143  0.31428571  0.17142857]
 [ 0.3        -0.1        -0.1       ]
 [ 0.09285714 -0.22142857 -0.00714286]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [12]:
b=np.zeros((3,1))
print("b\n",b)
Z=10*np.random.uniform(size=(5,1))
print("Z\n",np.round(Z,2))
I=np.eye(n)
print("I\n",I)


b
 [[0.]
 [0.]
 [0.]]
Z
 [[4.29]
 [3.26]
 [3.39]
 [3.82]
 [7.81]]
I
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


solution of homogeneous system of equations is x=(I-GA)*Z  where z is any random vector

In [13]:
sol=(I-G*A)*Z
print("solution of given system of linear equation having b(0,0,0) \n",np.round(sol,2))

solution of given system of linear equation having b(0,0,0) 
 [[13.23]
 [-0.  ]
 [11.23]
 [ 3.82]
 [ 7.81]]


solution of system having b vector (coefficient vector) (34 -45 129) is sol=G*b+(I-GA)*Z where z is any random vector

In [14]:
b=np.matrix([[34],[-45],[129]])
print("b\n",b)
Z=10*np.random.uniform(size=(5,1))
print("Z\n",np.round(Z,2))
I=np.eye(n)
print("I\n",I)
sol=G*b+(I-G*A)*Z
print("solution of given system of linear eqiation having b(34,-45,129) \n",np.round(sol,2))

b
 [[ 34]
 [-45]
 [129]]
Z
 [[7.4 ]
 [3.85]
 [1.29]
 [6.36]
 [2.17]]
I
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
solution of given system of linear eqiation having b(34,-45,129) 
 [[14.47]
 [ 1.8 ]
 [10.03]
 [ 6.36]
 [ 2.17]]
