## Q51
## Find the area and perimeter of a circle using functions. Prompt the user for input.

In [15]:
r = float(input("Enter the value of radious :"))
Area = 3.14*r*r
Perimeter = 2*3.14*r
print("Area Of Circle :",Area)
print("Perimeter Of Circle :",Perimeter)

Enter the value of radious :3
Area Of Circle : 28.259999999999998
Perimeter Of Circle : 18.84


## Q52
## Discuss the following methods supported by compiled regular expression objects: a) \verb"search()" b) \verb"match()" c) \verb"findall()"

In [ ]:
 ## Out of syllabus

## Q53
## Given the Coordinates(x,y) of a center of a Circle and its radius, write Python program to determine whether the Point lies inside the Circle, on the Circle or outside the Circle.

In [16]:
def isInside(circle_x, circle_y, r,x,y):
    if ((x - circle_x) * (y - circle_x) +                  #compare radious of circle distance of its centre.
        (y - circle_y) * (y - circle_y) <=r * r):
        return True;
    else:
        return False;

x = 3;
y = 3;
circle_x = 0;
circle_y = 1;
r = 2;
if(isInside(circle_x, circle_y, r,x,y)):
    print("Inside");
else:
    print("Outside");
    

Outside


## Q55
## How will you create a Package and import it? Explain it with an example program.

In [ ]:
## Out of Syllabus

## Q91
## Explain different ways to create an empty NumPy array in Python.

##  There are many ways to create empty numpy array in python..
## Syntax
## array=np.empty(shape,dtype(data type), order='c')

## Where ,
## Shape = it is used to determine shape of an empty array.
## dtype = it is used to define the data type of an empty array and it is optional parameter.
## order = it is used to determine which is order we store in multidimensional data..


In [8]:

import numpy as np
sample_array=np.empty((3,3))
print(sample_array)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.63234836e-321]
 [4.45042952e-307 2.55896735e-307 9.79101081e-307]]


In [10]:
A=np.zeros([3,4])
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
A=np.empty([4,4],dtype=float)
print(A)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22647084e-307]
 [1.42418987e-306 1.37961641e-306 1.60220528e-306 1.24611266e-306]
 [9.34598925e-307 1.24612081e-306 1.11260755e-306 1.60220393e-306]
 [1.51320640e-306 9.34609790e-307 1.86921279e-306 1.24610723e-306]]


In [13]:
A=np.empty([4,4],dtype=float,order='C')   ## we passed order (row style)
print(A)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22647084e-307]
 [1.42418987e-306 1.37961641e-306 1.60220528e-306 1.24611266e-306]
 [9.34598925e-307 1.24612081e-306 1.11260755e-306 1.60220393e-306]
 [1.51320640e-306 9.34609790e-307 1.86921279e-306 1.24610723e-306]]


In [14]:
A=np.empty(shape=2)
print(A)

[7.74860419e-304 7.74860419e-304]
