# Group No. 8
#### Prajakta Bhoi
#### Kirti Khalage
#### Gayatri Lakhotia

In [16]:
import numpy as np
import sympy as sp

# 1. To Demonstrate Maxima and Minima of Quadratic Form

In [24]:
A=np.array([[1,2,-3],[2,9,-2],[-3,-2,15]]);
print(A)
e,v=np.linalg.eig(A)
print("The eigen values are\n",e)
print("The eigen vectors are\n",v)

[[ 1  2 -3]
 [ 2  9 -2]
 [-3 -2 15]]
The eigen values are
 [ 0.10035761 16.38643349  8.5132089 ]
The eigen vectors are
 [[-0.96882016  0.22061526  0.11276708]
 [ 0.17929207  0.31012509  0.93363632]
 [-0.17100252 -0.92474393  0.34001001]]


### a. To check definiteness of quadratic form 

In [18]:
if all(e > 0) :
    print("The given Quadratic form is positive definite")
elif all(e >= 0) :
    print("The given Quadratic form is positive semi-definite")
elif all(e < 0 ):
    print("The given Quadratic form is negative definite")
elif all(e <= 0 ):
    print("The given Quadratic form is negative semi-definite")
else :
    print("The given Quadratic form is not a  definite")

The given Quadratic form is positive definite


### b. Obtain Algebric Multiplicity

In [22]:
from sympy import *
B = Matrix([[1,2,-3],[2,9,-2],[-3,-2,15]])
print(B.eigenvals())  #returns eigenvalues and their algebraic multiplicity

{25/3 - (161 + 3*sqrt(872742)*I)**(1/3)/3 - 199/(3*(161 + 3*sqrt(872742)*I)**(1/3)): 1, 25/3 - (-1/2 + sqrt(3)*I/2)*(161 + 3*sqrt(872742)*I)**(1/3)/3 - 199/(3*(-1/2 + sqrt(3)*I/2)*(161 + 3*sqrt(872742)*I)**(1/3)): 1, 25/3 - 199/(3*(-1/2 - sqrt(3)*I/2)*(161 + 3*sqrt(872742)*I)**(1/3)) - (-1/2 - sqrt(3)*I/2)*(161 + 3*sqrt(872742)*I)**(1/3)/3: 1}


### 2. To obtain maxima and minima of a quadratic form

In [23]:
m1=max(e)
print("The maximum of quadratic form is : ",m1)

The maximum of quadratic form is :  16.386433492269735


In [12]:
m2=min(e)
print("The minimum of quadratic form is : ",m2)

The minimum of quadratic form is :  0.10035760898119861


## 2.To demonstrate maxima and minima of the ratio of the quadratic form

In [ ]:
A=np.array([[2,10,-6],[10,-14,10],[-6,10,7]]);
print(A)
B=np.array([[6,3,-1],[3,17,-10],[-1,-10,6]]);
print(B)

er=np.linalg.eigvals(np.dot(np.linalg.inv(B),A))

print("The eigen values are\n",er)
er

### a. To check definiteness of ratio of quadratic form 

In [ ]:
if all(er > 0) :
    print("The given Quadratic form is positive definite")
elif all(er >= 0) :
    print("The given Quadratic form is positive semi definite")
elif all(er < 0 ):
    print("The given Quadratic form is negative definite")
elif all(er <= 0 ):
    print("The given Quadratic form is negative semi definite")
else :
    print("The given Quadratic form is not a  definite")

### b. To obtain maxima and minima of a ratio of quadratic form

In [8]:
mr1=max(er)
print("The maximum of ratio of quadratic form is : ",mr1)

The maximum of ratio of quadratic form is :  9.110250537824745


In [9]:
mr2=min(er)
print("The minimum of ratio of quadratic form is : ",mr2)

The minimum of ratio of quadratic form is :  -0.070250537824733
