In [1]:
pip install numpy



The following command must be run outside of the IPython shell:

    $ pip install numpy

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


In [2]:
import numpy as np
A=np.mat("1 1 3;1 3 1;3 1 1")


In [3]:
P,L=np.linalg.eig(A)

In [4]:
L1=np.diagflat(np.linalg.eigvals(A))

In [5]:
print(L1)

[[-2.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  2.]]


In [6]:
k1=5


In [7]:
print(L*L1**k1*(np.transpose(L)))

[[1031. 1031. 1063.]
 [1031. 1063. 1031.]
 [1063. 1031. 1031.]]
