# Topic 9

## Getting the vectors in column/row space and null space of the matrix.

## Group 18
1) Neha Patil <br>
2) Harshad Ahire <br>
3) Akil Ghodi <br>
4) Sai Rauf Maniyar <br>
5) Adipkumar Vishwakarma

### Que.1) Consider the following matrix

In [57]:
import numpy as np                     # Importing numpy package  as np.

In [58]:
A=np.array([[8,1,3,6],
                    [0,3,0,-9],
                    [-8,-1,-3,-16]])
print(A)                                        # Given matrix
m,n=A.shape                                # Order of the matrix

[[  8   1   3   6]
 [  0   3   0  -9]
 [ -8  -1  -3 -16]]


### i) Obtain two vectors in row and column space of A

### Column Space: 
Let A be an m x n matrix. Then the column space of A is a set of all linear combinations of columns of  A.

In [59]:
a_=np.dot(A,np.random.randn(n,1))                 # Product of the matrix A with the any random vector gives vector in column space of  the matrix A
b_=np.dot(A,np.random.randn(n,1))
print('The two vectors in column space of matrix A are\n',a_,'\n and\n',b_)

The two vectors in column space of matrix A are
 [[ 5.7893061 ]
 [ 8.21667128]
 [-2.3929828 ]] 
 and
 [[  6.98325959]
 [ -1.38959416]
 [-13.29971751]]


### Row Space: 
Let A be an m x n matrix. Then the row space of A is set of all linear combinations of rows of A.

In [60]:
c_=np.dot(np.random.randn(1,m),A)                 # Product of any random vectors transpose with matrix A  gives vector in row space of  the matrix A
d_=np.dot(np.random.randn(1,m),A)
print('The two vectors in row space of matrix A are\n',c_,'\n and\n',d_)

The two vectors in row space of matrix A are
 [[12.11770858 -0.55480374  4.54414072 20.84204759]] 
 and
 [[-1.57680242 -0.89959962 -0.59130091 -9.3538411 ]]


### ii) Obtain nullity of the matrix and hence obtain two vectors in null space of A

### Null Space:
The null space of any matrix A consists of all the vectors x such that Ax = 0 and **x = (I - GA)z** , where z is any arbitrary vector. 
  <br> Nullity is the rank of null space which is **' n - r '** where **n** is number of columns and **r** is rank of A.

In [61]:
r = np.linalg.matrix_rank(A)                # rank of A
print('Rank of A is',r)
nullity=n - r                                           # nullity of A
print('Nullityof the given matrix A is ',nullity)

Rank of A is 3
Nullityof the given matrix A is  1


In [62]:
G=np.zeros((m,n))                             # matrix of  zeros of order m by n
B=A[np.ix_([0,1,2],[1,2,3])]              # considering submatrix of A having rank r
r1=np.linalg.matrix_rank(B)

if r1==r:
    G[np.ix_([0,1,2],[1,2,3])]=np.linalg.inv(B).T    
    G=G.T
    print('The G inverse of A is\n',G)

c_=(np.eye(n,n)-G@A)@np.random.randn(n,1)       # Getting vectors in null space of A
d_=(np.eye(n,n)-G@A)@np.random.randn(n,1)
print('\nThe two vectors in null space of matrix A are\n',c_,'\n\n and\n\n',d_)

The G inverse of A is
 [[ 0.          0.          0.        ]
 [-0.3         0.33333333 -0.3       ]
 [ 0.63333333 -0.11111111  0.3       ]
 [-0.1        -0.         -0.1       ]]

The two vectors in null space of matrix A are
 [[-1.16874641]
 [ 0.        ]
 [ 3.11665709]
 [ 0.        ]] 

 and

 [[ 0.10690916]
 [ 0.        ]
 [-0.2850911 ]
 [ 0.        ]]


### Que. 2)

In [63]:
u=np.array([[6,16,-5]]).T
v=np.array([[0,2,-1]]).T
w=np.array([[2,2,0]]).T

In [64]:
A=np.concatenate((v,w),axis=1)          # forming matrix having columns as v and w.
r = np.linalg.matrix_rank(A)
A

array([[ 0,  2],
       [ 2,  2],
       [-1,  0]])

Here we find solution of the simultaneous linear equation Ax=u.

In [65]:
G=np.zeros((3,2))
B=A[np.ix_([0,1],[0,1])]
r1=np.linalg.matrix_rank(B)

if r1==r:
    G[np.ix_([0,1],[0,1])]=np.linalg.inv(B).T
    G=G.T
    print('The G inverse of A is\n',G)

x=G@u+(np.eye(2,2)-G@A)@np.random.randn(2,1)    # Finding solution

print('\nSince x= ',x[0],' and y=',x[1] ,'are real numbers. Thus vector u belongs to Span{v,w}')

The G inverse of A is
 [[-0.5  0.5  0. ]
 [ 0.5  0.   0. ]]

Since x=  [5.]  and y= [3.] are real numbers. Thus vector u belongs to Span{v,w}


### Que 3)

In [66]:
X1=np.array([[1,-1,1]]).T
X2=np.array([[3,4,-2]]).T
Y1=np.array([[9,5,-1]]).T
Y2=np.array([[-17,-11,3]]).T

In [67]:
A=np.concatenate((X1,X2),axis=1)          # forming matrix having columns as X1 and X2.
B=np.concatenate((Y1,Y2),axis=1)          # forming matrix having columns as Y1 and Y2.
print('A is \n',A,'\nB is\n',B)

A is 
 [[ 1  3]
 [-1  4]
 [ 1 -2]] 
B is
 [[  9 -17]
 [  5 -11]
 [ -1   3]]


In [68]:
r = np.linalg.matrix_rank(B)
G = np.zeros((3,2))
D = B[np.ix_([0,1],[0,1])]
r1 = np.linalg.matrix_rank(D)

if r1 == r:
    G[np.ix_([0,1],[0,1])]=np.linalg.inv(D).T
    G = G.T
    print('The G inverse of B is\n\n',G)

I = np.round(G@B)
print('\nHere product of G and matrix B is \n\n',I)

The G inverse of B is

 [[ 0.78571429 -1.21428571  0.        ]
 [ 0.35714286 -0.64285714  0.        ]]

Here product of G and matrix B is 

 [[ 1. -0.]
 [ 0.  1.]]


Consider, <br>
        A = BC <br>
GA = GBC         .... premultiplying by G-inverse of B <br>
        From above, we can see that GB = $I_2$ <br>
        $\therefore $ GA= IC = C <br>
Thus, C = GA

In [69]:
C=G@A
print('C is \n',C)

C is 
 [[ 2.  -2.5]
 [ 1.  -1.5]]


Since C exist, we conclude that the Span{X1, X2} is in same space as that of Span{Y1,Y2}.