In [2]:
import numpy as np

In [3]:
A=np.array([[2.5,0.58,0.4],
           [0.6,0.32,1],
           [0.2,0.84,4]])

In [4]:
print("A\n",A)

A
 [[2.5  0.58 0.4 ]
 [0.6  0.32 1.  ]
 [0.2  0.84 4.  ]]


In [5]:
r=np.linalg.matrix_rank(A)

In [6]:
print("r\n",r)

r
 2


In [7]:
B=A[np.ix_([0,r],[0,r])]

In [8]:
print("B\n",B)

B
 [[2.5 0.4]
 [0.2 4. ]]


In [9]:
H=np.linalg.matrix_rank(B)

In [10]:
print("H\n",H)

H
 2


In [11]:
size=np.shape(A)

In [13]:
print("size\n",size)
m=size[0]
n=size[1]

size
 (3, 3)


In [14]:
G=np.zeros((m,n))

In [15]:
print("G\n",G)

G
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
if H==r:
    G[np.ix_([0,r],[0,r])]=np.linalg.inv(B.T)
    G=G.T

In [17]:
print("The G inverse of given matrix is\n",G)

The G inverse of given matrix is
 [[ 0.40322581  0.         -0.04032258]
 [ 0.          0.          0.        ]
 [-0.02016129  0.          0.25201613]]


In [18]:
print("AGA\n",A.dot(G).dot(A))

AGA
 [[2.5  0.58 0.4 ]
 [0.6  0.32 1.  ]
 [0.2  0.84 4.  ]]


In [25]:
print("trace of GA",np.trace(G.dot(A)))

trace of GA 2.0


In [26]:
print("trace of AG",np.trace(A.dot(G)))

trace of AG 2.0
